name: mobile_app
description: A Smart Campus Hub student app (mobile)
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking + storage + token helpers
  http: ^1.2.0
  shared_preferences: ^2.2.0
  jwt_decoder: ^2.0.1
  google_fonts: ^6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
